### ISSUE TITLE
feature: avoid using fakeclientcommand and instead call the real zclass menu function

### ISSUE THREAD

**Issue by maxime1907** [srcdslab/sm-plugin-ZR_PersonalSkins#8]
https://github.com/srcdslab/sm-plugin-ZR_PersonalSkins/blob/d9c95b58154e1f68013d679b961ec8e6878b8dbf/addons/sourcemod/scripting/zr_personal_skins.sp#L224

**Comment by Rushaway** [comment]
ZR doesn't have api call for class menu `ClassMenuMain(client);`
